# Generated by Django 6.0.3 on 2026-04-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_status_alter_member_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Ugandan', 'Ugandan'), ('Rwandan', 'Rwandan'), ('Burundian', 'Burundian'), ('South Sudanese', 'South Sudanese'), ('Ethiopian', 'Ethiopian'), ('Somali', 'Somali'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
