# Generated by Django 6.0.3 on 2026-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.AddField(
            model_name='member',
            name='whyhycg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
