# Generated by Django 6.0.3 on 2026-04-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='donation_receipts/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='events/')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, to='membership.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('fundraising', 'Fundraising'), ('outreach', 'Outreach'), ('training', 'Training'), ('other', 'Other')], max_length=100)),
                ('attendees', models.IntegerField()),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/events/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='membership.event')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Income Statement'), ('expenditure', 'Expenditure Report'), ('balance', 'Balance Sheet'), ('audit', 'Audit Report')], max_length=50)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=50)),
                ('year', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/financial/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('economic', 'Economic Empowerment'), ('environment', 'Environment'), ('community', 'Community Development')], max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('lives_impacted', models.IntegerField()),
                ('beneficiaries', models.IntegerField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/impact/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_content', models.TextField(blank=True, help_text='Detailed impact report content', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to='membership.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('collections', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/membership/')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('special', 'Special')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.member')),
            ],
        ),
    ]
