# Generated by Django 6.0.3 on 2026-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_member_expires_at_member_is_deleted_member_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
