# Generated by Django 6.0.3 on 2026-05-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_announcement_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_transaction_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
